### ISSUE TITLE
Formatting disorder appears when printing Chinese

### ISSUE THREAD

**Issue by StudentWeis** [zakaria-chahboun/cute#6]
Formatting disorder appears when printing Chinese.

```go
package main

import "github.com/zakaria-chahboun/cute"

func main() {
	cute.Println("中文测试")
	cute.Println("English Test")
}
```

![problem_cute](https://s2.loli.net/2022/10/18/8HvJEbM2kReNQjt.png)

I think may be the reason what this happen is that the length of box is based on the length of UTF-8 code. But the length of Chinese's UTF-8 isn't the word length of it.

**Comment by zakaria-chahboun** [comment]
At this moment cute support only `ASCII` characters!

![image](https://user-images.githubusercontent.com/18173275/196330298-dd199fa4-ed17-49b8-af5b-70d3525be16c.png)

mmmm i'll figure it out how to fix this!

I think it's easy to support french or espanol language!

```go
// by replacing this
strings.Count("boire un café")
// with this
utf8.RuneCountInString("boire un café")
```

**Comment by StudentWeis** [comment]
Thanks for your work. ❤

> I think it's easy to support french or espanol language!

I think the Chinese language is the same.

**Comment by zakaria-chahboun** [comment]
@StudentWeis 

Chinese and other langs are supported now! it will be in the next version *inshallah*. Look at [Road map](https://github.com/zakaria-chahboun/cute/issues/5) list.

once i push the next version i'll notify you!

**Comment by StudentWeis** [comment]
This is great, thank you!

**Comment by zakaria-chahboun** [comment]
done
https://github.com/zakaria-chahboun/cute/releases/tag/v1.2.0
