### ISSUE TITLE
Not able to see symbols on mac OS terminal.

### ISSUE THREAD

**Issue by luminaire-dev** [zakaria-chahboun/cute#7]
Hey! I really love this formatter, makes things so clean and easy to look at. I noticed however that I can't see the same symbols on my mac OS terminal and instead see a [?]. Is it because of the font I'm using? Or is it something the package needs to support. 🤔 

<img width="393" alt="Screenshot 2024-05-25 at 3 18 58 AM" src="https://github.com/zakaria-chahboun/cute/assets/74129961/8791164d-c81f-444f-b82a-86b721037332">

###
Terminal encoding is set to UTF-8

<img width="319" alt="Screenshot 2024-05-25 at 3 24 32 AM" src="https://github.com/zakaria-chahboun/cute/assets/74129961/c0d5b3ff-f9ea-4e48-9515-fad5fc7484bb">

**Comment by zakaria-chahboun** [comment]
Hi @luminaire-dev 

I didn't test it on MacOs terminal before 
But it seems like just a font issue

My terminal uses *Meslo Nerd Font*, you can find it on this Link:
https://github.com/romkatv/powerlevel10k#fonts

I encourage you to install `Oh my zsh` with `powerlevel20k` theme on your terminal to have a good experience in general 

Thanks 🌹
